"""rename department

Revision ID: 58daa0f6abdd
Revises: 1ec7b36c7cb0
Create Date: 2024-04-03 23:35:39.990150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58daa0f6abdd'
down_revision = '1ec7b36c7cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('departments', 'department')
    # ### end Alembic commands ###
